version: '2.2'

services:
  apache:
    image: hammermc/nominatim-docker
    restart: always
    env_file:
      - osm.env
    command: nominatim-apache2
    volumes:
      - data:/data
      - run:/run
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache/local.php:/Nominatim/build/settings/local.php
      - ./osm-config.sh:/usr/local/etc/osm-config.sh
    tmpfs:
      - /tmp
    ports:
      - 80:80
    depends_on:
      - initdb

  postgres:
    image: hammermc/nominatim-docker
    restart: always
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    env_file:
      - osm.env
    volumes:
      - data:/data
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - run:/run
    tmpfs:
      - /tmp

  initdb:
    image: hammermc/nominatim-docker
    restart: "no"
    command: nominatim-initdb
    env_file:
      - osm.env
    environment:
      - REDOWNLOAD
      - REINITDB
    volumes:
      - data:/data
      - run:/run
      - ./osm-config.sh:/usr/local/etc/osm-config.sh
    tmpfs:
      - /tmp
    depends_on:
      - postgres

#  edit apache/local.php for correct update settings
  update:
    image: hammermc/nominatim-docker
    restart: "no"
    command: nominatim-updatedb
    env_file:
      - osm.env
    environment:
      - REDOWNLOAD
      - REINITDB
    volumes:
      - data:/data
      - run:/run
      - ./osm-config.sh:/usr/local/etc/osm-config.sh
    tmpfs:
      - /tmp
    depends_on:
      - postgres

volumes:
  data:
  postgres-data:
  run:

